line-length = 100

target-version = "py310"

exclude = [
    ".git",
    ".pytest_cache",
    "__pycache__",
    "venv",
    ".venv",
    "build",
    "dist",
    "*.egg-info",
]

[lint]

select = [
    "E",     
    "W",     
    "F",     
    "I",     
    "N",     
    "UP",    
    "B",     
    "C4",    
    "SIM",   
    "RUF",   
]

ignore = [
    "E501",  
]

[lint.per-file-ignores]
"__init__.py" = ["F401"]  

[format]

quote-style = "double"

indent-style = "space"

line-ending = "lf"
